# Generated by Django 4.2.1 on 2023-05-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Members',
        ),
    ]
