# Generated by Django 4.2.1 on 2023-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/Web_image')),
            ],
        ),
        migrations.CreateModel(
            name='LatestB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/web1_image')),
            ],
        ),
        migrations.CreateModel(
            name='Teamoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/Members1_image')),
            ],
        ),
    ]
