# Generated by Django 4.2.1 on 2023-06-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoffer',
            name='about',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamoffer',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamoffer',
            name='profession',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
