# Generated by Django 4.2.1 on 2023-06-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='Email1',
        ),
    ]
