# Generated by Django 4.2.1 on 2023-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_email_contact_email1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email1',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='email',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
