# Generated by Django 4.2.1 on 2023-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_contact_email1_alter_email_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email1', models.EmailField(max_length=40)),
                ('Website', models.CharField(max_length=200)),
                ('Comment', models.CharField(max_length=250)),
            ],
        ),
    ]
